// Decompiled with JetBrains decompiler
// Type: EDGE.TicketTools.TicketPopulator.TemplateViewsTool
// Assembly: EDGEforREVIT, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 8F55B9C3-A92E-41C0-AD06-820A67FFC8AF
// Assembly location: C:\ProgramData\Autodesk\Revit\Addins\2024\PTAC_EDGE_BUNDLE\EDGEforREVIT.dll

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace EDGE.TicketTools.TicketPopulator;

public class TemplateViewsTool : Form
{
  private IContainer components;
  private CheckBox chkPlan;
  private CheckBox chkSectionA;
  private CheckBox chkSectionB;
  private CheckBox chkElevTop;
  private CheckBox chkElevBottom;
  private CheckBox chkElevLeft;
  private CheckBox chkElevRight;
  private CheckBox chkElevFront;
  private CheckBox chkElevBack;
  private ComboBox cmbPlan;
  private ComboBox cmbSectionA;
  private ComboBox cmbSectionB;
  private ComboBox cmbElevTop;
  private ComboBox cmbElevBottom;
  private ComboBox cmbElevLeft;
  private ComboBox cmbElevRight;
  private ComboBox cmbElevFront;
  private ComboBox cmbElevBack;
  private ComboBox cmbTitleblock;
  private Label label1;
  private Label label2;
  private ComboBox cmbScale;
  private CheckBox checkBox1;
  private ComboBox cmbPlaceBOM;
  private Button btnBOMTemplate;

  public TemplateViewsTool() => this.InitializeComponent();

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    this.chkPlan = new CheckBox();
    this.chkSectionA = new CheckBox();
    this.chkSectionB = new CheckBox();
    this.chkElevTop = new CheckBox();
    this.chkElevBottom = new CheckBox();
    this.chkElevLeft = new CheckBox();
    this.chkElevRight = new CheckBox();
    this.chkElevFront = new CheckBox();
    this.chkElevBack = new CheckBox();
    this.cmbPlan = new ComboBox();
    this.cmbSectionA = new ComboBox();
    this.cmbSectionB = new ComboBox();
    this.cmbElevTop = new ComboBox();
    this.cmbElevBottom = new ComboBox();
    this.cmbElevLeft = new ComboBox();
    this.cmbElevRight = new ComboBox();
    this.cmbElevFront = new ComboBox();
    this.cmbElevBack = new ComboBox();
    this.cmbTitleblock = new ComboBox();
    this.label1 = new Label();
    this.label2 = new Label();
    this.cmbScale = new ComboBox();
    this.checkBox1 = new CheckBox();
    this.cmbPlaceBOM = new ComboBox();
    this.btnBOMTemplate = new Button();
    this.SuspendLayout();
    this.chkPlan.AutoSize = true;
    this.chkPlan.Location = new Point(40, 200);
    this.chkPlan.Name = "chkPlan";
    this.chkPlan.Size = new Size(152, 24);
    this.chkPlan.TabIndex = 2;
    this.chkPlan.Text = "Horizontal Detail";
    this.chkPlan.UseVisualStyleBackColor = true;
    this.chkSectionA.AutoSize = true;
    this.chkSectionA.Location = new Point(40, 241);
    this.chkSectionA.Name = "chkSectionA";
    this.chkSectionA.Size = new Size(149, 24);
    this.chkSectionA.TabIndex = 3;
    this.chkSectionA.Text = "Detail Section A";
    this.chkSectionA.UseVisualStyleBackColor = true;
    this.chkSectionB.AutoSize = true;
    this.chkSectionB.Location = new Point(40, 282);
    this.chkSectionB.Name = "chkSectionB";
    this.chkSectionB.Size = new Size(149, 24);
    this.chkSectionB.TabIndex = 4;
    this.chkSectionB.Text = "Detail Section B";
    this.chkSectionB.UseVisualStyleBackColor = true;
    this.chkElevTop.AutoSize = true;
    this.chkElevTop.Location = new Point(40, 323);
    this.chkElevTop.Name = "chkElevTop";
    this.chkElevTop.Size = new Size(131, 24);
    this.chkElevTop.TabIndex = 5;
    this.chkElevTop.Text = "Elevation Top";
    this.chkElevTop.UseVisualStyleBackColor = true;
    this.chkElevBottom.AutoSize = true;
    this.chkElevBottom.Location = new Point(40, 364);
    this.chkElevBottom.Name = "chkElevBottom";
    this.chkElevBottom.Size = new Size(156, 24);
    this.chkElevBottom.TabIndex = 6;
    this.chkElevBottom.Text = "Elevation Bottom";
    this.chkElevBottom.UseVisualStyleBackColor = true;
    this.chkElevLeft.AutoSize = true;
    this.chkElevLeft.Location = new Point(40, 405);
    this.chkElevLeft.Name = "chkElevLeft";
    this.chkElevLeft.Size = new Size(132, 24);
    this.chkElevLeft.TabIndex = 7;
    this.chkElevLeft.Text = "Elevation Left";
    this.chkElevLeft.UseVisualStyleBackColor = true;
    this.chkElevRight.AutoSize = true;
    this.chkElevRight.Location = new Point(40, 446);
    this.chkElevRight.Name = "chkElevRight";
    this.chkElevRight.Size = new Size(142, 24);
    this.chkElevRight.TabIndex = 8;
    this.chkElevRight.Text = "Elevation Right";
    this.chkElevRight.UseVisualStyleBackColor = true;
    this.chkElevFront.AutoSize = true;
    this.chkElevFront.Location = new Point(40, 487);
    this.chkElevFront.Name = "chkElevFront";
    this.chkElevFront.Size = new Size(142, 24);
    this.chkElevFront.TabIndex = 9;
    this.chkElevFront.Text = "Elevation Front";
    this.chkElevFront.UseVisualStyleBackColor = true;
    this.chkElevBack.AutoSize = true;
    this.chkElevBack.Location = new Point(40, 528);
    this.chkElevBack.Name = "chkElevBack";
    this.chkElevBack.Size = new Size(140, 24);
    this.chkElevBack.TabIndex = 10;
    this.chkElevBack.Text = "Elevation Back";
    this.chkElevBack.UseVisualStyleBackColor = true;
    this.cmbPlan.FormattingEnabled = true;
    this.cmbPlan.Location = new Point(218, 198);
    this.cmbPlan.Name = "cmbPlan";
    this.cmbPlan.Size = new Size(305, 28);
    this.cmbPlan.TabIndex = 11;
    this.cmbSectionA.FormattingEnabled = true;
    this.cmbSectionA.Location = new Point(218, 239);
    this.cmbSectionA.Name = "cmbSectionA";
    this.cmbSectionA.Size = new Size(305, 28);
    this.cmbSectionA.TabIndex = 12;
    this.cmbSectionB.FormattingEnabled = true;
    this.cmbSectionB.Location = new Point(218, 280);
    this.cmbSectionB.Name = "cmbSectionB";
    this.cmbSectionB.Size = new Size(305, 28);
    this.cmbSectionB.TabIndex = 13;
    this.cmbElevTop.FormattingEnabled = true;
    this.cmbElevTop.Location = new Point(218, 321);
    this.cmbElevTop.Name = "cmbElevTop";
    this.cmbElevTop.Size = new Size(305, 28);
    this.cmbElevTop.TabIndex = 14;
    this.cmbElevBottom.FormattingEnabled = true;
    this.cmbElevBottom.Location = new Point(218, 358);
    this.cmbElevBottom.Name = "cmbElevBottom";
    this.cmbElevBottom.Size = new Size(305, 28);
    this.cmbElevBottom.TabIndex = 15;
    this.cmbElevLeft.FormattingEnabled = true;
    this.cmbElevLeft.Location = new Point(218, 401);
    this.cmbElevLeft.Name = "cmbElevLeft";
    this.cmbElevLeft.Size = new Size(305, 28);
    this.cmbElevLeft.TabIndex = 16 /*0x10*/;
    this.cmbElevRight.FormattingEnabled = true;
    this.cmbElevRight.Location = new Point(218, 444);
    this.cmbElevRight.Name = "cmbElevRight";
    this.cmbElevRight.Size = new Size(305, 28);
    this.cmbElevRight.TabIndex = 17;
    this.cmbElevFront.FormattingEnabled = true;
    this.cmbElevFront.Location = new Point(218, 485);
    this.cmbElevFront.Name = "cmbElevFront";
    this.cmbElevFront.Size = new Size(305, 28);
    this.cmbElevFront.TabIndex = 18;
    this.cmbElevBack.FormattingEnabled = true;
    this.cmbElevBack.Location = new Point(218, 526);
    this.cmbElevBack.Name = "cmbElevBack";
    this.cmbElevBack.Size = new Size(305, 28);
    this.cmbElevBack.TabIndex = 19;
    this.cmbTitleblock.FormattingEnabled = true;
    this.cmbTitleblock.Location = new Point(36, 619);
    this.cmbTitleblock.Name = "cmbTitleblock";
    this.cmbTitleblock.Size = new Size(371, 28);
    this.cmbTitleblock.TabIndex = 20;
    this.label1.AutoSize = true;
    this.label1.Location = new Point(36, 596);
    this.label1.Name = "label1";
    this.label1.Size = new Size(75, 20);
    this.label1.TabIndex = 21;
    this.label1.Text = "Titleblock";
    this.label2.AutoSize = true;
    this.label2.Location = new Point(36, 122);
    this.label2.Name = "label2";
    this.label2.Size = new Size(49, 20);
    this.label2.TabIndex = 23;
    this.label2.Text = "Scale";
    this.cmbScale.FormattingEnabled = true;
    this.cmbScale.Location = new Point(36, 148);
    this.cmbScale.Name = "cmbScale";
    this.cmbScale.Size = new Size(239, 28);
    this.cmbScale.TabIndex = 22;
    this.checkBox1.AutoSize = true;
    this.checkBox1.Location = new Point(40, 701);
    this.checkBox1.Name = "checkBox1";
    this.checkBox1.Size = new Size(160 /*0xA0*/, 24);
    this.checkBox1.TabIndex = 24;
    this.checkBox1.Text = "Place Ticket BOM";
    this.checkBox1.UseVisualStyleBackColor = true;
    this.cmbPlaceBOM.FormattingEnabled = true;
    this.cmbPlaceBOM.Location = new Point(230, 701);
    this.cmbPlaceBOM.Name = "cmbPlaceBOM";
    this.cmbPlaceBOM.Size = new Size(285, 28);
    this.cmbPlaceBOM.TabIndex = 25;
    this.btnBOMTemplate.Location = new Point(521, 700);
    this.btnBOMTemplate.Name = "btnBOMTemplate";
    this.btnBOMTemplate.Size = new Size(49, 29);
    this.btnBOMTemplate.TabIndex = 26;
    this.btnBOMTemplate.Text = "...";
    this.btnBOMTemplate.UseVisualStyleBackColor = true;
    this.AutoScaleDimensions = new SizeF(9f, 20f);
    this.AutoScaleMode = AutoScaleMode.Font;
    this.ClientSize = new Size(689, 924);
    this.Controls.Add((Control) this.btnBOMTemplate);
    this.Controls.Add((Control) this.cmbPlaceBOM);
    this.Controls.Add((Control) this.checkBox1);
    this.Controls.Add((Control) this.label1);
    this.Controls.Add((Control) this.cmbTitleblock);
    this.Controls.Add((Control) this.label2);
    this.Controls.Add((Control) this.cmbScale);
    this.Controls.Add((Control) this.cmbElevBack);
    this.Controls.Add((Control) this.cmbElevFront);
    this.Controls.Add((Control) this.cmbElevRight);
    this.Controls.Add((Control) this.cmbElevLeft);
    this.Controls.Add((Control) this.cmbElevBottom);
    this.Controls.Add((Control) this.cmbElevTop);
    this.Controls.Add((Control) this.cmbSectionB);
    this.Controls.Add((Control) this.cmbSectionA);
    this.Controls.Add((Control) this.cmbPlan);
    this.Controls.Add((Control) this.chkElevBack);
    this.Controls.Add((Control) this.chkElevFront);
    this.Controls.Add((Control) this.chkElevRight);
    this.Controls.Add((Control) this.chkElevLeft);
    this.Controls.Add((Control) this.chkElevBottom);
    this.Controls.Add((Control) this.chkElevTop);
    this.Controls.Add((Control) this.chkSectionB);
    this.Controls.Add((Control) this.chkSectionA);
    this.Controls.Add((Control) this.chkPlan);
    this.Name = nameof (TemplateViewsTool);
    this.Text = "Edge^R Ticket Template Views Tool";
    this.ResumeLayout(false);
    this.PerformLayout();
  }
}
